### ISSUE TITLE
Boot from Any Other NTFS Partition

### ISSUE THREAD

**Issue by areebqaisar** [pbatard/uefi-ntfs#12]
Hello,
Well this is not exactly an issue, but just asking for help.
It can successfully boot the first NTFS Partition, it finds. 
I have a specific scenario in which I have to boot from 2nd or 3rd etc NTFS partition it finds.
Where exactly in the Code, I need to set this parameter (partition no) to achieve this functionality ?
Thanks.

**Comment by pbatard** [comment]
Then you might be interested with [this fork of UEFI:NTFS](https://github.com/linnaea/uefi-ntfs-multiboot).

Otherwise, it's all [in there](https://github.com/pbatard/uefi-ntfs/blob/master/boot.c#L406-L441).
Note that there isn't a specific: _List all NTFS partitions in an array, then look for the first one_ as you seem to be expecting so you'll have to add a counter yourself.

As I believe I answered your question, I will close this issue.
