### ISSUE TITLE
Doesn't work on newer computers.

### ISSUE THREAD

**Issue by jclab-joseph** [pbatard/uefi-ntfs#43]
At least the 9th generation and earlier seem to work well.
The NTFS volume is not found on the same disk on another computer (latest generation (13th generation)).

I used bootx64_signed.efi of the latest driver, v2.3.

MODEL: SAMSUNG NT950XFG-KG71S
BIOS : AMI P04VAD.350.230623.MP
CPU  : Intel 13th i7-1360P
DISK : NVMe MZVL2512HCJQ

**Comment by pbatard** [comment]
1. If this was true (i.e. if this was, as you __assume__, an issue linked to newer CPUs), I would get loads of reports from people unable to install Windows using Rufus on modern computers, since Rufus relies on UEFI:NTFS for that, which I don't. __Therefore__, we can safely conclude that your generalisation that this is a global issue rather than something that is linked to the specific environment you used, is incorrect.
2. UEFI is designed to be CPU agnostic. And UEFI:NTFS is specs compliant with the UEFI specs. Therefore, if a CPU really had an issue booting UEFI-compliant software, then the issue would be with the CPU and not the software. Furthermore, in most cases, most UEFI booting issues are caused by the UEFI firmware from the machine, and have nothing to do with the CPU. And there again, if the platform UEFI firmware fails to boot software that is UEFI-specs compliant, then the issue is with the platform UEFI firmware.
3. Since I have no clue how you created your UEFI:NTFS media, and again, I get no reports whatsoever from Rufus usage of UEFI:NTFS incompatibility with "newer CPUs" (whereas Rufus gets downloaded close to 3 million times each month, and I'd venture to say that at least a third of these downloads are for modern Windows installation, which __will__ create a media with UEFI:NTFS, therefore I would most certainly get tons of reports if what you state was true), I will ask you to please recreate your media using [Rufus](https://rufus.ie), making sure you click on _Show advanced drive properties_, so that you then get a selectable  _UEFI:NTFS_ entry under _Boot selection_ which is what you should use to create the media. Then you should place a `EFI\Boot\bootx64.efi` on the NTFS partition (a different one from the UEFI:NTFS one, as the point of UEFI:NTFS is to chain load a third-party UEFI bootloader residing on the NTFS partition &mdash; you could for instance use a GRUB UEFI bootloader) and see if that gets booted. Especially, your statement that _"The NTFS volume is not found on the same disk on another computer"_ seems to hint that you simply did not create your UEFI:NTFS media properly.
