### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by erikkrb** [pbatard/uefi-ntfs#44]
i get the error secure boot violation error code 26![20240317_130655.jpg](https://github.com/pbatard/uefi-ntfs/assets/151580743/31fec4ef-48f5-495f-91c7-ba125c8a78a9)

**Comment by pbatard** [comment]
That means that the `efi\boot\bootz64.efi` __on the NTFS partition__ (i.e. **NOT** the one provided by this project, which did pass Secure Boot validation because otherwise, you wouldn't see any of this output) has failed Secure Boot validation.

You will need to find out why.

As this is clearly not an issue related to this project (anybody can drop a random bootloader on an NTFS partition and end up with this error) I will close this issue.
